### ISSUE TITLE
Error in get_descendents with curies

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model-toolkit#154]
v. 1.1.2

If I lookup descendents of `noncoding RNA product` it works:
 ```
tk.get_descendants("noncoding RNA product")
['noncoding RNA product', 'microRNA', 'siRNA']
```

But if I use the curie form (which came from a response to `tk.get_descendents(...,formatted=True)`) then it fails:
```
tk.get_descendants("biolink:NoncodingRNAProduct")
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/opt/anaconda3/envs/redistpf/lib/python3.12/site-packages/bmt/toolkit.py", line 739, in get_descendants
    raise ValueError("not a valid biolink component")
```

**Comment by cbizon** [comment]
The types and predicates that I found that have this problem are: 
```
Error with type: biolink:NoncodingRNAProduct
Error with type: biolink:MicroRNA
Error with type: biolink:SiRNA
Error with predicate: biolink:gene_fusion_with
Error with predicate: biolink:genetic_neighborhood_of
```

I think that on the type side it's not happy when there are consecutive capital letters and on the predicate side when there are underscores in the non-curie name of the predicate.  That latter case should probably be changed in the model as well...?

**Comment by redst4r** [comment]
ran into the exact same issue, for example,
```python
tk.parent('microRNA')
# -> 'biolink:NoncodingRNAProduct'
```
works fine, yet

```python
tk.parent('biolink:microRNA')
```
return `None`

**Comment by redst4r** [comment]
Looks like there's two problems going on:
1. `utils.parse_name()` is screwing up the class names:
	1. `parse_name('biolink:MicroRNA') == "microrna"`  (biolink classname in yaml is `microRNA`)
	2. `parse_name('biolink:NoncodingRNAProduct') == "noncodingrna product"`  (class name is `noncoding RNA product`)
	3. `parse_name('biolink:gene_fusion_with') == 'gene fusion with'` (should be `gene_fusion_with`)
	4. ...

2. the inconsistency between using the biolink prefix and not using it, e..g 
   ```python 
   B.get_ancestors('biolink:microRNA') != B.get_ancestors('microRNA')
   ```

## Issue 1
No idea how to fix this systematically (with all that CamelCase, Snake_case etc conversion going on); maybe hardcode those few cases (`microRNA`, `siRNA`, `NoncodingRNAProduct`) to return the proper class names in biolink.
## Issue 2
Issue 2 can be tracked down to this [function](https://github.com/biolink/biolink-model-toolkit/blob/00db3c0b96c1c1b34e7fea71453da6c1d631f2d9/bmt/toolkit.py#L940) (the logic seems convoluted):
```python
def get_element(self, name: str) -> Optional[Element]:
        parsed_name = parse_name(name)
        logger.debug(parsed_name)
        element = self.view.get_element(parsed_name)
        # A: checking against aliases
        if element is None and self.view.all_aliases() is not None:
            if parsed_name.startswith("biolink:"):
                parsed_name = parsed_name.replace("biolink:", "")
                parsed_name = parsed_name.replace("_", " ")
            for e in self.view.all_aliases():
                if name in self.view.all_aliases()[e] or parsed_name in self.view.all_aliases()[e]:
                    element = self.view.get_element(e)
        if element is None and "_" in name:
            element = self.get_element(name.replace("_", " "))
        # B: checking against biolink elements via lower_case matches
        if element is None:
            for e, el in self.view.all_elements().items():
                if el.name.lower() == name.lower():
                    element = el
```
Notes:
- `parsed_name` (which removes the 'biolink:' prefix) is utilized only in part A (checking against aliases)
- `if parsed_name.startswith("biolink:")` will never be true btw, since parse_name strips the prefix
### Scenarios
#### name ="biolink:microRNA"
- `element = self.view.get_element(parsed_name)` fails to find anything
- as the microRNA-class doesn't have any aliases, nothing matches in part A
- no matches against the `self.view.all_elements()` in lower case, as `name` still carries the 'biolink:' prefix
#### name ="microRNA"
- `element = self.view.get_element(parsed_name)` fails to find anything
	- note that `self.view.get_element('microrna')` (parsed_name) fails while `self.view.get_element('microRNA')` would have succeeded.
- as microRNA doesn't have any aliases, nothing matches in part A
- it matches in lowercase against "microrna"
### Possible fix
Not really sure how to fix this systematically either, I'm not familiar with the naming conventions. A quick and easy fix would be stripping the 'biolink:' prefix (== comparing to `parsed_name`) in part B:

```python
        if element is None:
            for e, el in self.view.all_elements().items():
                if el.name.lower() == name.lower() or el.name.lower() == parsed_name.lower():
                    element = el
```
